"""
Django settings for magazine_backend project.

Generated by 'django-admin startproject' using Django 5.2.8.
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load .env file (local and on PythonAnywhere free account)
load_dotenv(BASE_DIR / ".env")


# --- SECURITY / ENVIRONMENT ---
# Use environment variables for secrets and debug so we don't leak them to repo
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-local-dev-key')
DEBUG = os.environ.get('DJANGO_DEBUG', 'True') == 'True'

# Hosts: include local defaults. Add production hosts (pythonanywhere, vercel) before deploying.
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'shadhii.pythonanywhere.com',
    # 'yourproject.vercel.app',           # <-- add frontend domain when ready
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third party
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',

    # Your apps
    'posts',
]

# Media settings (user uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
}


# Middleware
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise to serve static files (works well on simple hosts like PythonAnywhere)
    'whitenoise.middleware.WhiteNoiseMiddleware',

    # CORS middleware should be as high as possible and before CommonMiddleware
    'corsheaders.middleware.CorsMiddleware',

    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',

    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'magazine_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # add template dirs if you have any
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'magazine_backend.wsgi.application'


# Database (left as your current sqlite — fine for small development)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'   # change to 'Asia/Kolkata' if preferred
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
STATIC_URL = '/static/'
# Folder where `collectstatic` will copy static files to (map on PythonAnywhere)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise staticfiles storage (compressed + manifest)
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- CORS / CSRF (frontend integration) ---
# Allow these origins to make requests (add Vercel domain & localhost)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    # "https://yourproject.vercel.app",    # <-- add your deployed frontend domain
    # "https://www.yourproject.vercel.app",
]

# If your frontend makes stateful POST requests (CSRF), add trusted origins:
CSRF_TRUSTED_ORIGINS = [
    # "https://yourproject.vercel.app",   # <-- add when frontend domain is known
]

# Optional: allow credentials (cookies) from CORS origin if needed
CORS_ALLOW_CREDENTIALS = True
